# 인구 조사 데이터로 인종 예측하기

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [124]:
df = pd.read_csv('./datasets/adult.data', header=None)
df.shape

(32561, 15)

In [125]:
df.isna().sum().sum()

0

In [126]:
race = df[8]
set(race)

{' Amer-Indian-Eskimo', ' Asian-Pac-Islander', ' Black', ' Other', ' White'}

In [127]:
x = df.drop(columns=[2, 8]) # 의미없는 2번 컬럼과 y 컬럼 제외
y = race.map({' Amer-Indian-Eskimo': 0, ' Asian-Pac-Islander': 1,
         ' Black':2, ' Other':3, ' White':4})
x.shape, y.shape

((32561, 13), (32561,))

1. 누락 데이터 처리
1. X, Y 분리, 카테고리를 원핫 인코딩
1. 배열로 변환, float32 타입 변환
1. 사이킷런 LogisticRegression 으로 학습 및 성능 체크
1. 텐서플로 직접 구현

In [128]:
x_dum = pd.get_dummies(x)
x_dum = np.array(x_dum).astype(np.float32)
y = np.array(y)
x_dum.shape, type(x_dum), type(y) # 텐서플로는 numpy 만 읽을 수 있다

((32561, 104), numpy.ndarray, numpy.ndarray)

In [129]:
from sklearn.linear_model import LogisticRegression
#model = LogisticRegression(solver='lbfgs', max_iter=200,multi_class='auto').fit(x_dum, y)
model = LogisticRegression().fit(x_dum, y)
print('accuracy', model.score(x_dum, y))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

accuracy 0.8734989711618194

In [ ]:
from sklearn.preprocessing import OneHotEncoder
y_2d = y.reshape([-1,1]) 
y_hot = OneHotEncoder().fit_transform(y_2d) # # tf.one_hot() 과 같다
y_hot = y_hot.toarray() # sparse matrix > dense matrix
y_hot.shape

In [ ]:
w = tf.Variable(tf.random_normal(shape=[104, 5])) #[104개 특징, 5개의 클래스] 
b = tf.Variable(tf.random_normal(shape=[5]))#5개의 클래스 
xn = x_dum / tf.reduce_max(x_dum)
z = tf.matmul(xn, w) + b 
h = tf.nn.softmax(z)
h = tf.clip_by_value(h, 1e-8, 1 - 1e-8) # log(0) 이 되지 않도록 안전장치
cost = - tf.reduce_mean(y_hot * tf.log(h) + (1-y_hot) * tf.log(1-h))
regularization = 1e-3 * tf.reduce_mean(w**2)
predict_class = tf.math.argmax(h, axis=1, output_type=tf.int32) #[0, 2]
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict_class, y), tf.float32)) 
train = tf.train.GradientDescentOptimizer(0.5).minimize(cost+regularization)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [ ]:
for i in range(1000):
    _, c, a = sess.run([train, cost, accuracy])
    if i%100 == 0: print(i, c, a)
print('w : 상관관계 ', sess.run(w))

In [79]:
weight = sess.run(w)
weight.shape

(104, 5)

In [80]:
col_name = pd.get_dummies(x).columns.values
len(col_name), col_name.shape

(104, (104,))

In [81]:
d = pd.DataFrame(weight)

In [82]:
d.columns = set(race)
d.set_index(col_name)

,Asian-Pac-Islander,Other,White,Amer-Indian-Eskimo,Black
0,-0.626123,-0.839252,-0.568518,-0.965661,-0.562979
4,-0.392450,-0.653408,-0.621373,0.593650,-1.165223
10,-1.338175,0.395253,0.192901,-1.106798,0.668396
11,0.188518,-0.342175,0.280743,-0.480473,1.498428
12,-2.101917,-0.203840,0.772987,1.056976,0.308852
1_ ?,-0.323664,0.398586,-1.663887,-1.021099,1.183541
1_ Federal-gov,1.145826,-1.560326,-0.074274,-0.649132,0.969502
1_ Local-gov,2.049340,1.079450,0.714968,0.960439,-0.302685
1_ Never-worked,0.507475,-0.150548,-1.848548,0.333915,-1.319711
1_ Private,-1.355100,2.136464,-0.644070,1.244481,0.272604
1_ Self-emp-inc,-0.597677,-0.048252,-1.828147,0.302674,-0.284938
1_ Self-emp-not-inc,0.629450,1.016090,-0.123684,0.847707,-1.852196
1_ State-gov,1.183918,0.709381,0.425610,-0.530857,0.754621
1_ Without-pay,0.507879,0.221276,1.123666,0.206914,0.705395
3_ 10th,0.801417,-0.063550,-0.657689,0.006049,-0.041968
3_ 11th,-0.032930,-1.045610,0.014295,-2.158234,0.283946
3_ 12th,-0.847578,1.088189,0.247521,1.157049,0.148533
3_ 1st-4th,0.434191,1.875973,-0.365022,0.954215,-0.787723
3_ 5th-6th,0.801595,0.222639,-0.620509,-1.962622,0.170700
3_ 7th-8th,0.241987,0.349374,-0.815832,0.533787,0.664229
3_ 9th,1.068477,-1.031747,1.634860,-0.441091,-1.722250
3_ Assoc-acdm,0.744985,1.351213,0.484662,0.729371,-0.107894
3_ Assoc-voc,1.443237,-1.184815,0.378895,0.661885,-0.292258
3_ Bachelors,2.436590,-0.066336,-0.402063,-0.884242,0.954075
3_ Doctorate,0.033912,1.477507,0.282274,0.087391,-0.889489
3_ HS-grad,-1.717556,-1.518490,-0.876971,-0.293304,-0.023499
3_ Masters,0.546746,-1.373793,0.301243,2.248263,-0.250809
3_ Preschool,-1.525968,0.698838,-3.557082,-1.147102,-1.018502
3_ Prof-school,-1.350388,-0.010757,0.120637,0.241695,-0.317644
3_ Some-college,-0.444735,0.653470,1.719872,0.847915,-0.712787
...,...,...,...,...,...
13_ Haiti,-0.173745,1.395881,-0.028973,2.467042,0.615705
13_ Holand-Netherlands,0.632502,0.083075,-1.218490,-1.106663,0.838308
13_ Honduras,0.583643,-0.177799,-0.037122,0.106908,-0.432390
13_ Hong,0.702771,0.216034,-0.087901,0.035053,-1.381054
13_ Hungary,-0.109872,0.288119,1.200848,0.443952,-0.373100
13_ India,0.534998,0.072161,-0.530742,-0.857913,0.124152
13_ Iran,-0.816583,0.409636,-0.417961,-0.121746,-0.245290
13_ Ireland,0.231015,-0.371600,2.434178,-0.107904,-0.689961
13_ Italy,-0.092776,-1.280878,-0.813215,0.615046,-1.503778
13_ Jamaica,0.592452,-0.814566,-2.879041,1.193738,-0.607286
13_ Japan,0.527437,2.015256,0.519462,0.075299,1.002872
13_ Laos,1.069158,0.415079,0.641111,0.782590,0.464974
13_ Mexico,0.708717,-0.698430,1.439001,0.635375,1.544542
13_ Nicaragua,0.614503,0.012851,-0.821576,0.535988,-0.967933
13_ Outlying-US(Guam-USVI-etc),0.486462,-1.765617,1.834489,1.453563,0.481302
13_ Peru,-0.576001,-0.505358,-0.316977,0.252177,0.628220
13_ Philippines,1.191558,0.369494,1.590519,0.288545,-2.216384
13_ Poland,-0.609806,1.563833,-0.174142,0.874902,1.257463
13_ Portugal,-1.899174,0.505728,-0.696409,0.915121,-0.864018
13_ Puerto-Rico,0.853650,0.520377,1.367893,-0.367322,2.111404
13_ Scotland,0.813394,-0.908220,-0.374580,1.106243,-2.801752
13_ South,-1.559819,-1.549500,-0.656996,-1.829149,-0.120326
13_ Taiwan,0.718632,0.827839,1.278028,0.909658,-1.387488
13_ Thailand,-1.182471,-1.105405,-0.109039,0.388796,0.099606
13_ Trinadad&Tobago,1.623190,0.364878,-1.531349,0.381180,2.039465
13_ United-States,-0.987258,0.920803,0.442169,-2.463421,-0.793789
13_ Vietnam,-1.307924,0.736931,-0.055149,0.701320,2.403053
13_ Yugoslavia,1.477176,-0.759337,-0.630493,-0.457031,-0.238939
14_ <=50K,0.980949,1.447114,0.921926,1.688495,-1.072175
14_ >50K,-0.552605,-0.920081,0.000870,-1.369497,-0.748350

## 자동차 검사 결과 예측하기

In [86]:
df = pd.read_csv('./datasets/car.data', header=None)
df.shape

(1728, 7)

In [91]:
df.columns = ['buying price', 'maintenance','doors','persons','lug_boot','safe','y']

In [93]:
df.head()

  buying price maintenance doors persons lug_boot  safe      y
0        vhigh       vhigh     2       2    small   low  unacc
1        vhigh       vhigh     2       2    small   med  unacc
2        vhigh       vhigh     2       2    small  high  unacc
3        vhigh       vhigh     2       2      med   low  unacc
4        vhigh       vhigh     2       2      med   med  unacc

In [ ]:
df.isna().sum().sum()

In [ ]:
df_dum = pd.get_dummies(df)
df_dum.columns

In [104]:
x = np.array(df_dum.iloc[:, :-4])
y = np.array(df_dum.iloc[:, -4:])
y_argmax = np.argmax(y, axis=-1)
x.shape, y.shape

((1728, 21), (1728, 4))

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression().fit(x, y_argmax)
print('accuracy', model.score(x, y_argmax))

In [113]:
w = tf.Variable(tf.random_normal(shape=[21, 4])) #[21개 특징, 4개의 클래스] 
b = tf.Variable(tf.random_normal(shape=[4]))#4개의 클래스 
xn = x / tf.reduce_max(x)
z = tf.matmul(xn, w) + b 
h = tf.nn.softmax(z)
h = tf.clip_by_value(h, 1e-8, 1 - 1e-8) # log(0) 이 되지 않도록 안전장치
cost = - tf.reduce_mean(y * tf.log(h) + (1-y) * tf.log(1-h))
regularization = 1e-3 * tf.reduce_mean(w**2)
predict_class = tf.math.argmax(h, axis=1, output_type=tf.int32) #[0, 2]
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict_class, y_argmax), tf.float32)) 
train = tf.train.GradientDescentOptimizer(0.5).minimize(cost+regularization)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [114]:
for i in range(1000):
    _, c, a = sess.run([train, cost, accuracy])
    if i%100 == 0: print(i, c, a)

0 0.9495914 0.28819445
100 0.21634613 0.8142361
200 0.18358842 0.8553241
300 0.16657852 0.8709491
400 0.15436229 0.8767361
500 0.14531383 0.880787
600 0.13847715 0.8865741
700 0.13311775 0.8912037
800 0.1287559 0.8952546
900 nan 0.22222222